version: '3.8'
services:
  api:
    build: ./app
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vsic_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
